[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tfg-recomendador-uja"
version = "0.1.0"
description = "Recomendador de titulaciones de la Universidad de Jaén basado en RAG"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Samuel Blanco Palmero"}
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
]

[project.urls]
Repository = "https://github.com/samubp10/tfg-recomendador-uja"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
